# Generated by Django 5.1.7 on 2025-03-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customuser_barcode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_session'),
        ),
    ]
