# Generated by Django 5.1.7 on 2025-03-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_session_unique_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='barcode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
