# Generated by Django 5.1.5 on 2025-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_student_course_studentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
