# Generated by Django 5.1.5 on 2025-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_leavereportstudent_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='staff_leave_attachments/'),
        ),
    ]
