# Generated by Django 5.2.1 on 2025-06-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_leavereportstaff_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
