# Generated by Django 5.1.7 on 2025-03-30 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_admin_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nfc_id',
            field=models.CharField(blank=True, help_text='NFC ID from the student/staff card', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='NFCAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'date')},
            },
        ),
    ]
