# Generated by Django 5.1.5 on 2025-04-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_customuser_nfc_id_nfcattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nfc_id',
        ),
        migrations.DeleteModel(
            name='NFCAttendance',
        ),
    ]
